/* ============================================================================
   CARD DATA — Hunting for Black Holes & Neutron Stars
   School on Gravity 2026 · Day 2 interactive exercise
   ----------------------------------------------------------------------------
   TO ADD A NEW CARD: copy an existing { ... } block, edit the fields, done.
   The page (bhns_cards.html) reads this file and renders everything.

   OBJECT CARD fields:
     id       : short label shown on the card ("A1"); use "" for extras
     cat      : must match a key of OBJECT_CATEGORIES
     name     : card title
     why      : what it is / why it matters
     signal   : tell-tale signal & detection method
     answers  : example facilities — ONLY shown with ?answers=1 in the URL
     extra    : true => rendered as a bonus card (dashed outline)

   TELESCOPE CARD fields:
     band     : must match a key of TELESCOPE_BANDS
     name     : facility name
     core     : true => ★ core-deck facility
     img      : path to the card image, e.g. "bhns_card_images/lisa.jpg"
                (save your own images into the bhns_card_images/ folder;
                a colored monogram placeholder is shown if the file is missing)
     wiki     : English Wikipedia page title — only used for the
                "Wikipedia" link on the card (handy image source too)
     tstart   : first year of operations (number, drives the timeline bar)
     tend     : last year (number) or null = ongoing / open-ended
     future   : true => planned / under construction (hatched timeline bar)
     spec     : spectral coverage bar. kind: "em" (log10 photon frequency, Hz),
                "gw" (log10 GW frequency, Hz) or "nu" (log10 neutrino energy, eV).
                segs: one or more [lo, hi] segments on that log scale.
                Cheat sheet (log10 Hz): 1 GHz=9 · 1 µm=14.48 · 550 nm=14.74 ·
                1 keV=17.38 · 1 MeV=20.38 · 1 GeV=23.38 · 1 TeV=26.38
     freq     : frequency / wavelength coverage (text on the card)
     product  : what you measure (spectroscopy, astrometry, timing, ...)
     notes    : status / context (rollout plans, launch dates, quirks)
     use      : key BH/NS use case — ONLY shown with ?answers=1
     refs     : list of { t: "Author + year", u: ADS link or null }
   ========================================================================== */

const OBJECT_CATEGORIES = {
  A: { label: "A · Progenitors & precursors", color: "#E98A3C" },
  B: { label: "B · Explosive endpoints",      color: "#D6336C" },
  C: { label: "C · Single compact objects",   color: "#9D4EDD" },
  D: { label: "D · Compact objects in binaries", color: "#3E63DD" },
  E: { label: "E · DCO mergers & multi-messenger signals", color: "#22223B" },
};

const OBJECT_CARDS = [
  // ---------- A. Progenitors & precursors ----------
  { id: "A1", cat: "A", name: "Massive OB(A) stars & their multiplicity",
    why: "Every BH/NS was once a massive star; binary fraction and orbital-parameter distributions set the initial conditions for everything that follows.",
    signal: "Multi-epoch spectroscopy → radial-velocity (RV) curves; astrometric orbits; eclipses.",
    answers: "SDSS-V (BOSS 600k OBA stars), Gaia, VLT, 4MOST/WEAVE, TESS" },
  { id: "A2", cat: "A", name: "Stripped (helium) stars — the 'missing stripped stars'",
    why: "Predicted product of binary mass transfer and progenitors of stripped-envelope SNe; long elusive at intermediate masses (Götberg et al. 2018; Drout et al. 2023).",
    signal: "UV excess in composite spectra; UV photometry + optical spectroscopy.",
    answers: "UVEX, HST (UV spectroscopy), Swift-UVOT, GALEX (archival), SDSS-V/APOGEE" },
  { id: "A3", cat: "A", name: "RSG/YSG/BSG supernova progenitors — the 'missing RSG problem'",
    why: "Direct progenitor detections in pre-explosion images; apparent lack of Type II-P progenitors with M_ZAMS ≳ 18–20 M☉.",
    signal: "Pre-explosion archival imaging; IR photometric monitoring of nearby galaxies.",
    answers: "HST, JWST, Roman, Rubin (LSST), Spitzer (archival)" },
  { id: "A4", cat: "A", name: "Luminous red novae (common-envelope ejections)",
    why: "The only direct observational window on common-envelope evolution — the key uncertainty in the CE formation channel (Howitt et al. 2020).",
    signal: "Optical/IR transients with characteristic red, double-peaked light curves.",
    answers: "Rubin (LSST), ZTF, Gaia alerts, ATLAS/ASAS-SN, Roman (extragalactic)" },
  { extra: true, id: "", cat: "A", name: "Pre-SN outbursts & LBV-like eruptions",
    why: "Episodic mass loss in the final years before collapse shapes circumstellar interaction (Type IIn) and remnant masses.",
    signal: "Precursor detections in high-cadence survey light curves.",
    answers: "ZTF, Rubin (LSST), ATLAS/ASAS-SN" },

  // ---------- B. Explosive endpoints ----------
  { id: "B1", cat: "B", name: "Hydrogen-rich (Type II) supernovae",
    why: "The default death of single massive stars; rates and progenitor masses calibrate which stars explode vs collapse silently.",
    signal: "Optical time-domain photometry + spectroscopic classification.",
    answers: "Rubin (LSST), ZTF, BlackGEM, 4MOST/SDSS-V spectroscopic follow-up" },
  { id: "B2", cat: "B", name: "Stripped-envelope SNe (IIb/Ib/Ic)",
    why: "Trace binary-stripped progenitors; their high rate is a pillar of the 'missing stripped star' argument.",
    signal: "Photometry + spectroscopy (He/H line diagnostics).",
    answers: "ZTF, Rubin (LSST), spectroscopic facilities (VLT, 4MOST)" },
  { id: "B3", cat: "B", name: "Broad-lined Ic SNe & long GRBs (collapsars)",
    why: "Deaths of rapidly rotating stripped stars — the link between angular-momentum transport and BH birth.",
    signal: "γ-ray prompt emission → X-ray/optical/radio afterglow chain; SN spectroscopy.",
    answers: "Fermi, Swift, SVOM, CTAO (TeV afterglows), VLT/ELT, VLA" },
  { id: "B4", cat: "B", name: "Superluminous SNe & (P)PISN candidates",
    why: "Observational probes of the pair-instability regime that carves the upper BH mass gap.",
    signal: "Deep wide-field surveys; slow, luminous light curves; high-z searches.",
    answers: "Rubin (LSST), Roman (high-z), Euclid, JWST spectroscopy" },
  { id: "B5", cat: "B", name: "Failed SNe / 'disappearing' massive stars",
    why: "Direct evidence for silent collapse to a BH (e.g. N6946-BH1); sets f_explode vs f_collapse.",
    signal: "Repeated imaging of nearby galaxies: a star that vanishes (with a faint transient).",
    answers: "HST, JWST, Roman, Rubin (LSST)" },
  { extra: true, id: "", cat: "B", name: "Shock breakout & early shock-cooling emission",
    why: "First photons from a SN: progenitor radius and final mass-loss diagnostics, hours-timescale physics.",
    signal: "Wide-field UV/X-ray monitors with minutes-level alerts.",
    answers: "ULTRASAT, Einstein Probe, UVEX, Swift" },
  { extra: true, id: "", cat: "B", name: "Galactic core-collapse neutrino burst",
    why: "Only direct probe of the collapsing core and proto-NS cooling (SN 1987A); will fire ~hours before light.",
    signal: "MeV neutrino burst detection; SNEWS early-warning network.",
    answers: "Super-K/Hyper-K, IceCube, KM3NeT, DUNE/JUNO" },
  { extra: true, id: "", cat: "B", name: "Natal kicks (pulsar velocities)",
    why: "Pulsar proper motions calibrate the kick distributions (Hobbs Maxwellian) that decide binary survival — see the Day 1 kick lottery!",
    signal: "VLBI astrometry & timing proper motions of young pulsars.",
    answers: "VLBA/ngVLA, SKA-Mid, FAST/MeerKAT timing, Gaia (runaway stars)" },

  // ---------- C. Single compact objects ----------
  { id: "C1", cat: "C", name: "Radio pulsars (incl. millisecond & recycled)",
    why: "Clocks that reveal NS spins, B-fields, binary history (recycling) and post-SN orbits.",
    signal: "Beamformed radio searches; pulsar timing.",
    answers: "SKA-Low/Mid, FAST, MeerKAT, CHIME, LOFAR, Parkes/GBT/Effelsberg" },
  { id: "C2", cat: "C", name: "Magnetars & fast radio bursts (FRBs)",
    why: "Extreme-B NSs; SGR 1935+2154 tied (some) FRBs to magnetars — NS tell-tales at cosmological distances.",
    signal: "Radio bursts + X-ray/soft-γ outbursts; localization to host galaxies.",
    answers: "CHIME, FAST, DSA-2000, SKA, Einstein Probe, Fermi-GBM, NICER" },
  { id: "C3", cat: "C", name: "Isolated stellar-mass black holes",
    why: "The 'silent majority': most single BHs emit nothing — microlensing is the only census (OGLE-2011-BLG-0462, Sahu/Lam 2022).",
    signal: "Long-timescale photometric microlensing + astrometric deflection.",
    answers: "OGLE, Roman (Bulge Time Domain Survey: 100s–1000 expected), Gaia, HST, Rubin" },
  { extra: true, id: "", cat: "C", name: "Thermal emission from NS surfaces — the EoS",
    why: "Pulse-profile modelling gives simultaneous mass & radius → dense-matter equation of state (complements GW tidal deformability).",
    signal: "Soft X-ray timing & phase-resolved spectroscopy.",
    answers: "NICER, XMM-Newton, NewAthena, (XRISM spectroscopy)" },

  // ---------- D. Compact objects in binaries ----------
  { id: "D1", cat: "D", name: "Low-mass X-ray binaries & transient outbursts",
    why: "Accreting BH/NS systems; BH spin & mass measurements; recycling channel for ms pulsars.",
    signal: "X-ray monitoring of outbursts; radio jets; quiescent-state RV spectroscopy.",
    answers: "Einstein Probe, MAXI, Swift, NICER, IXPE (geometry), VLA/SKA (jets)" },
  { id: "D2", cat: "D", name: "High-mass X-ray binaries (Be-XRB, SG-XRB)",
    why: "Immediate progenitors of double compact objects — the 'caught in the act' phase between the two SNe (Fortin et al. 2023).",
    signal: "X-ray timing/spectroscopy + optical spectroscopy of the donor; orbital periods.",
    answers: "Einstein Probe, Swift, NuSTAR, NICER, Chandra/XMM + VLT/SDSS-V for donors" },
  { id: "D3", cat: "D", name: "Dormant (detached) BH/NS + star binaries",
    why: "Gaia BH1–3, VFTS 243: the quiet systems that dominate by number and stress-test binary evolution models (El-Badry et al. 2023+).",
    signal: "Astrometric wobble; RV curves of single-lined binaries; ellipsoidal variability; self-lensing.",
    answers: "Gaia (astrometry), SDSS-V/4MOST/VLT (RVs), TESS & Rubin (ellipsoidal/self-lensing)" },
  { id: "D4", cat: "D", name: "Spider pulsars (redbacks & black widows)",
    why: "Recycled ms pulsars ablating their companions; endpoint of LMXB evolution and hosts of the most massive NSs.",
    signal: "Radio timing + optical light curves/RVs of the irradiated companion.",
    answers: "FAST, MeerKAT, SKA; Rubin/VLT for companions; Fermi-LAT (γ-ray selection)" },
  { id: "D5", cat: "D", name: "Binary & double pulsars (Hulse–Taylor, J0737−3039)",
    why: "Decades-long indirect GW proof; masses to 10⁻⁴ precision; tests of GR; direct NSNS progenitor census in the Galaxy.",
    signal: "Precision pulsar timing of relativistic binaries.",
    answers: "MeerKAT/SKA-Mid, FAST, Parkes, GBT, Effelsberg" },
  { extra: true, id: "", cat: "D", name: "Ultraluminous X-ray sources (ULXs)",
    why: "Super-Eddington accretion; ULX pulsars proved some are NSs — candidates for HMXB→DCO evolution at low Z.",
    signal: "X-ray imaging of nearby galaxies; pulsation searches.",
    answers: "Chandra (imaging), NuSTAR (pulsations), XMM-Newton" },

  // ---------- E. DCO mergers & multi-messenger signals ----------
  { id: "E1", cat: "E", name: "Merging stellar-mass binary black holes",
    why: "Stellar binary black hole populations: the mass & spin distributions, mass gaps, and formation-channel diagnostics.",
    signal: "GW strain (chirp); possible AGN-disc EM flares for the dynamical channel.",
    answers: "LIGO–Virgo–KAGRA → ET/CE; ZTF/Rubin (AGN flare candidates)" },
  { id: "E2", cat: "E", name: "Merging NSNS & BHNS: GW + kilonova + sGRB + afterglow",
    why: "GW170817: the holistic showcase — GW masses & distance, γ-ray jet, UV/optical/IR kilonova (r-process!), X-ray/radio structured-jet afterglow, H₀.",
    signal: "GW alert → γ-ray prompt → wide-field optical/UV tiling → spectroscopy → radio/X-ray monitoring.",
    answers: "LVK/ET/CE + Fermi/Swift/SVOM + Rubin/BlackGEM/GOTO/ZTF + ULTRASAT/UVEX + JWST/ELT/VLT + VLA/SKA + Chandra" },
  { id: "E3", cat: "E", name: "EMRIs, IMBH & supermassive BH binaries",
    why: "Extends the BH mass ladder; PTAs detect the nHz background of SMBH binaries; LISA hears their mergers.",
    signal: "nHz timing residuals; mHz GW strain; (VLBI imaging of SMBHs).",
    answers: "PTAs (NANOGrav/EPTA/PPTA/MPTA), LISA, EHT/ngEHT" },
  { extra: true, id: "", cat: "E", name: "r-process fossil record",
    why: "Abundances in metal-poor halo stars & dwarf galaxies record the integrated history of NS mergers — 'GW astronomy with stellar spectra'.",
    signal: "High-resolution optical spectroscopy (Eu, Sr, actinides).",
    answers: "VLT/ELT, 4MOST/WEAVE, SDSS-V; JWST (kilonova nebular spectra, e.g. Te in GRB 230307A)" },
  { extra: true, id: "", cat: "E", name: "Galactic double white dwarfs & early-inspiral binaries (multiband GW)",
    why: "LISA verification binaries; stellar-mass BBHs caught years before LVK/ET sees the merger → multiband astronomy.",
    signal: "mHz GW strain; optical eclipsing DWD surveys.",
    answers: "LISA; ZTF/Rubin (eclipsing DWDs); Gaia" },
];

const TELESCOPE_BANDS = {
  gw:    { label: "GW & other messengers", color: "#22223B" },
  radio: { label: "Radio",                 color: "#E5B910" },
  optTD: { label: "Optical/IR · imaging & time domain", color: "#D6336C" },
  optSp: { label: "Optical/IR · astrometry & spectroscopy", color: "#E98A3C" },
  uv:    { label: "Ultraviolet",           color: "#9D4EDD" },
  xray:  { label: "X-ray",                 color: "#3E63DD" },
  gamma: { label: "Gamma-ray",             color: "#B5179E" },
};

// shorthand for ADS links
const ADS = id => `https://ui.adsabs.harvard.edu/abs/${id}/abstract`;
const ADSQ = q => `https://ui.adsabs.harvard.edu/search/q=${encodeURIComponent(q)}&sort=citation_count desc`;

const TELESCOPE_CARDS = [
  // ---------- GW & other messengers ----------
  { band: "gw", core: true, name: "LIGO–Virgo–KAGRA (LVK)", wiki: "LIGO",
    img: "bhns_card_images/ligo_virgo_kagra_lvk.png",
    tstart: 2015, tend: null, spec: { kind: "gw", segs: [[1.0, 3.7]] },
    freq: "~10 Hz – few kHz (GW)", product: "GW strain: chirp masses, spins, distances, sky maps, low-latency alerts",
    notes: "O4 ongoing; O5 with A+/A♯ upgrades in the late 2020s.",
    use: "Merging BBH/NSNS/BHNS; triggers the entire EM follow-up chain",
    refs: [ { t: "Aasi + 2015", u: ADS("arXiv:1411.4547") }, { t: "Acernese + 2015", u: ADS("arXiv:1408.3978") }, { t: "Akutsu + 2021", u: ADS("arXiv:2005.05574") } ] },
  { band: "gw", core: true, name: "Einstein Telescope (ET)", wiki: "Einstein Telescope",
    img: "bhns_card_images/einstein_telescope_et.jpg",
    tstart: 2035, tend: null, future: true, spec: { kind: "gw", segs: [[0.5, 4.0]] },
    freq: "~3 Hz – 10 kHz (GW)", product: "3G underground GW interferometry; early warning for NSNS",
    notes: "Planned (ESFRI); site decision pending.",
    use: "BBH to z ~ 10–100: the full cosmic merger history",
    refs: [ { t: "Punturo + 2010", u: ADS("2010CQGra..27s4002P") }, { t: "ET Blue Book 2025", u: ADS("arXiv:2503.12263") } ] },
  { band: "gw", core: false, name: "Cosmic Explorer (CE)", wiki: "Cosmic Explorer (gravitational wave observatory)",
    img: "bhns_card_images/cosmic_explorer_ce.jpg",
    tstart: 2035, tend: null, future: true, spec: { kind: "gw", segs: [[0.7, 3.6]] },
    freq: "~5 Hz – 4 kHz (GW)", product: "3G GW; 20/40 km L-shaped arms",
    notes: "Proposed (US).",
    use: "With ET: detects essentially every stellar-mass merger in the Universe",
    refs: [ { t: "Evans + 2021", u: ADS("arXiv:2109.09882") } ] },
  { band: "gw", core: true, name: "LISA", wiki: "Laser Interferometer Space Antenna",
    img: "bhns_card_images/lisa.jpg",
    tstart: 2035, tend: 2040, future: true, spec: { kind: "gw", segs: [[-4, -1]] },
    freq: "0.1 mHz – 0.1 Hz (GW)", product: "Space-based GW interferometry (2.5 Mkm arms)",
    notes: "Adopted by ESA Jan 2024; launch ~2035; 4.5-yr science phase (extendable).",
    use: "SMBH mergers, EMRIs, ~10⁴ Galactic double WDs, multiband stellar BBH",
    refs: [ { t: "Colpi + 2024", u: ADS("arXiv:2402.07571") } ] },
  { band: "gw", core: true, name: "Pulsar Timing Arrays (→ IPTA)", wiki: "Pulsar timing array",
    img: "bhns_card_images/pulsar_timing_arrays_ipta.jpg",
    tstart: 2004, tend: null, spec: { kind: "gw", segs: [[-9, -7]] },
    freq: "~1–100 nHz (GW)", product: "Decades-long precision timing of millisecond pulsars",
    notes: "NANOGrav, EPTA+InPTA, PPTA, MPTA, CPTA; evidence for the nHz GW background announced 2023.",
    use: "nHz background from SMBH binaries; Galactic-scale GW detector",
    refs: [ { t: "Agazie + 2023", u: ADS("arXiv:2306.16213") } ] },
  { band: "gw", core: false, name: "IceCube / KM3NeT (→ Gen2)", wiki: "IceCube Neutrino Observatory",
    img: "bhns_card_images/icecube_km3net_gen2.jpg",
    tstart: 2011, tend: null, spec: { kind: "nu", segs: [[12, 16]] },
    freq: "TeV–PeV neutrinos", product: "High-energy neutrino alerts & point-source searches",
    notes: "KM3NeT partially operating in the Mediterranean; IceCube-Gen2 planned for the 2030s.",
    use: "Hadronic jet physics; ν limits on NS mergers & GRBs",
    refs: [ { t: "Aartsen + 2017", u: ADS("arXiv:1612.05093") }, { t: "Adrián-Martínez + 2016", u: ADS("arXiv:1601.07459") } ] },
  { band: "gw", core: false, name: "Super-K (SK-Gd) → Hyper-Kamiokande", wiki: "Hyper-Kamiokande",
    img: "bhns_card_images/super_k_sk_gd_hyper_kamiokande.jpg",
    tstart: 1996, tend: null, spec: { kind: "nu", segs: [[6, 8]] },
    freq: "MeV neutrinos", product: "Burst detection; SNEWS early warning (hours before shock breakout)",
    notes: "Super-K operating since 1996 (now Gd-loaded); Hyper-K from ~2028.",
    use: "Galactic core-collapse SN: explosion mechanism, proto-NS cooling",
    refs: [ { t: "Hyper-K design report 2018", u: ADS("arXiv:1805.04163") }, { t: "Al Kharusi + 2021 (SNEWS 2.0)", u: ADS("arXiv:2011.00035") } ] },

  // ---------- Radio ----------
  { band: "radio", core: true, name: "SKA-Low (Australia)", wiki: "Square Kilometre Array",
    img: "bhns_card_images/ska_low_australia.jpeg",
    tstart: 2027, tend: null, future: true, spec: { kind: "em", segs: [[7.70, 8.54]] },
    freq: "50–350 MHz", product: "Aperture-array imaging + beamformed pulsar/FRB searches",
    notes: "Under construction; science verification ~2027, early ops late 2020s; SKA2 envisioned ~2040s.",
    use: "Order-of-magnitude pulsar census increase; FRBs; steep-spectrum pulsars",
    refs: [ { t: "Braun + 2019", u: ADS("arXiv:1912.12699") } ] },
  { band: "radio", core: true, name: "SKA-Mid (South Africa)", wiki: "Square Kilometre Array",
    img: "bhns_card_images/ska_mid_south_africa.jpg",
    tstart: 2027, tend: null, future: true, spec: { kind: "em", segs: [[8.54, 10.19]] },
    freq: "350 MHz – 15.4 GHz", product: "Dish-array imaging; high-precision pulsar timing",
    notes: "Same staged rollout as SKA-Low (AA2 → AA*); incorporates MeerKAT.",
    use: "PTA sensitivity boost; relativistic binary pulsars; merger afterglows",
    refs: [ { t: "Braun + 2019", u: ADS("arXiv:1912.12699") } ] },
  { band: "radio", core: false, name: "MeerKAT", wiki: "MeerKAT",
    img: "bhns_card_images/meerkat.jpg",
    tstart: 2018, tend: null, spec: { kind: "em", segs: [[8.76, 9.54]] },
    freq: "0.58–3.5 GHz (UHF/L/S)", product: "Imaging + timing programmes (MeerTime, TRAPUM)",
    notes: "Will be absorbed into SKA-Mid.",
    use: "GW170817 late-time afterglow; new relativistic binary pulsars",
    refs: [ { t: "Jonas + 2016", u: ADSQ("Jonas MeerKAT 2016") }, { t: "Bailes + 2020", u: ADS("arXiv:2005.14366") } ] },
  { band: "radio", core: true, name: "FAST (500 m)", wiki: "Five-hundred-meter Aperture Spherical Telescope",
    img: "bhns_card_images/fast_500_m.jpg",
    tstart: 2020, tend: null, spec: { kind: "em", segs: [[7.85, 9.48]] },
    freq: "70 MHz – 3 GHz", product: "Single-dish searches & timing (world's most sensitive)",
    notes: "",
    use: ">1000 new pulsars; FRB monitoring; NSNS progenitor census",
    refs: [ { t: "Nan + 2011", u: ADS("arXiv:1105.3794") }, { t: "Jiang + 2019", u: ADS("arXiv:1903.06324") } ] },
  { band: "radio", core: true, name: "CHIME", wiki: "Canadian Hydrogen Intensity Mapping Experiment",
    img: "bhns_card_images/chime.jpg",
    tstart: 2018, tend: null, spec: { kind: "em", segs: [[8.60, 8.90]] },
    freq: "400–800 MHz", product: "Daily transit survey of the northern sky; real-time burst pipeline",
    notes: "CHORD planned as successor.",
    use: "FRB factory (1000s); FRB 20200428 from Galactic magnetar SGR 1935+2154",
    refs: [ { t: "CHIME/FRB Collab. 2018", u: ADS("arXiv:1803.11235") }, { t: "CHIME/FRB Collab. 2020", u: ADS("arXiv:2005.10324") } ] },
  { band: "radio", core: false, name: "LOFAR", wiki: "LOFAR",
    img: "bhns_card_images/lofar.jpg",
    tstart: 2010, tend: null, spec: { kind: "em", segs: [[7.00, 8.38]] },
    freq: "10–90 + 110–240 MHz", product: "Low-frequency imaging + beamformed searches",
    notes: "LOFAR 2.0 upgrade ~2026.",
    use: "Steep-spectrum & long-period pulsars; FRB scattering",
    refs: [ { t: "van Haarlem + 2013", u: ADS("arXiv:1305.3550") } ] },
  { band: "radio", core: false, name: "VLA → ngVLA", wiki: "Very Large Array",
    img: "bhns_card_images/vla_ngvla.jpg",
    tstart: 1980, tend: null, spec: { kind: "em", segs: [[9.00, 11.06]] },
    freq: "1–50 GHz / 1.2–116 GHz", product: "µJy interferometric imaging; VLBI astrometry",
    notes: "ngVLA early operations expected in the 2030s.",
    use: "GW170817 superluminal jet motion; XRB jets; pulsar proper motions (kicks!)",
    refs: [ { t: "Murphy + 2018", u: ADSQ("Murphy ngVLA science 2018") }, { t: "Mooley + 2018", u: ADS("arXiv:1810.12927") } ] },
  { band: "radio", core: false, name: "DSA-2000", wiki: "Deep Synoptic Array",
    img: "bhns_card_images/dsa_2000.jpg",
    tstart: 2028, tend: null, future: true, spec: { kind: "em", segs: [[8.85, 9.30]] },
    freq: "0.7–2 GHz", product: "2000-dish 'radio camera': all-sky survey + commensal pulsar/FRB search",
    notes: "Planned; construction this decade.",
    use: "Radio transient & FRB localization machine",
    refs: [ { t: "Hallinan + 2019", u: ADS("arXiv:1907.07648") } ] },
  { band: "radio", core: false, name: "EHT → ngEHT", wiki: "Event Horizon Telescope",
    img: "bhns_card_images/eht_ngeht.jpg",
    tstart: 2017, tend: null, spec: { kind: "em", segs: [[11.36, 11.54]] },
    freq: "230/345 GHz (VLBI)", product: "Horizon-scale imaging (µas resolution)",
    notes: "ngEHT expansion planned.",
    use: "M87* & Sgr A* shadows — the supermassive end of the BH family",
    refs: [ { t: "EHT Collab. 2019", u: ADS("arXiv:1906.11238") }, { t: "EHT Collab. 2022", u: ADSQ("Event Horizon Telescope 2022 Sagittarius A* first results") } ] },
  { band: "radio", core: false, name: "ALMA", wiki: "Atacama Large Millimeter Array",
    img: "bhns_card_images/alma.jpg",
    tstart: 2011, tend: null, spec: { kind: "em", segs: [[10.92, 11.98]] },
    freq: "84–950 GHz", product: "mm/sub-mm imaging & photometry",
    notes: "",
    use: "Afterglow SEDs & jet calorimetry; reverse shocks",
    refs: [ { t: "Wootten & Thompson 2009", u: ADSQ("Wootten Thompson ALMA 2009") } ] },

  // ---------- Optical / IR — imaging & time domain ----------
  { band: "optTD", core: true, name: "Vera C. Rubin Observatory (LSST)", wiki: "Vera C. Rubin Observatory",
    img: "bhns_card_images/vera_c_rubin_observatory_lsst.jpg",
    tstart: 2025, tend: 2036, spec: { kind: "em", segs: [[14.46, 14.97]] },
    freq: "320–1050 nm (ugrizy)", product: "18,000 deg² photometric survey; ~10 million alerts/night; ToO GW follow-up",
    notes: "First look 2025; 10-yr LSST survey ~2026–2036.",
    use: "SNe of all flavours, kilonovae, LRNe, ellipsoidal & self-lensing CO binaries, µ-lensing",
    refs: [ { t: "Ivezić + 2019", u: ADS("arXiv:0805.2366") } ] },
  { band: "optTD", core: true, name: "ZTF", wiki: "Zwicky Transient Facility",
    img: "bhns_card_images/ztf.jpg",
    tstart: 2018, tend: null, spec: { kind: "em", segs: [[14.52, 14.87]] },
    freq: "g, r, i (400–900 nm)", product: "3760 deg²/h survey; public alert stream",
    notes: "",
    use: "SN factory; AGN-disc BBH flare candidates; eclipsing DWDs",
    refs: [ { t: "Bellm + 2019", u: ADS("arXiv:1902.01932") } ] },
  { band: "optTD", core: true, name: "BlackGEM (+ MeerLICHT)", wiki: "BlackGEM",
    img: "bhns_card_images/blackgem_meerlicht.jpg",
    tstart: 2023, tend: null, spec: { kind: "em", segs: [[14.50, 14.93]] },
    freq: "u–z optical, 2.7 deg² each", product: "Optical counterpart search; MeerLICHT co-points with MeerKAT (simultaneous radio–optical)",
    notes: "La Silla; 3 telescopes, expandable to 15.",
    use: "Kilonova hunting for O4/O5 GW alerts (P.I. Groot)",
    refs: [ { t: "Groot + 2024", u: ADSQ("Groot BlackGEM telescope array 2024") } ] },
  { band: "optTD", core: false, name: "GOTO", wiki: "Gravitational-wave Optical Transient Observer",
    img: "bhns_card_images/goto.jpg",
    tstart: 2022, tend: null, spec: { kind: "em", segs: [[14.63, 14.87]] },
    freq: "Wide-field optical (L band, 400–700 nm)", product: "GW sky-map tiling within minutes",
    notes: "Sites on La Palma + in Australia.",
    use: "Kilonova candidate identification",
    refs: [ { t: "Steeghs + 2022", u: ADS("arXiv:2110.05539") } ] },
  { band: "optTD", core: false, name: "ATLAS / ASAS-SN", wiki: "Asteroid Terrestrial-impact Last Alert System",
    img: "bhns_card_images/atlas_asas_sn.jpg",
    tstart: 2014, tend: null, spec: { kind: "em", segs: [[14.50, 14.90]] },
    freq: "Optical, all-sky daily cadence", product: "Bright-transient discovery & nightly monitoring",
    notes: "",
    use: "Nearby SNe, Galactic novae, XRB optical outbursts",
    refs: [ { t: "Tonry + 2018", u: ADS("arXiv:1802.00879") }, { t: "Shappee + 2014", u: ADS("arXiv:1310.2241") } ] },
  { band: "optTD", core: true, name: "TESS", wiki: "Transiting Exoplanet Survey Satellite",
    img: "bhns_card_images/tess.jpg",
    tstart: 2018, tend: null, spec: { kind: "em", segs: [[14.48, 14.70]] },
    freq: "600–1000 nm", product: "Continuous space-based photometry (27-day sectors)",
    notes: "Nearly all-sky coverage in 27-day sectors.",
    use: "Ellipsoidal variability of dormant CO binaries; early SN light curves",
    refs: [ { t: "Ricker + 2015", u: ADS("arXiv:1406.0151") } ] },
  { band: "optTD", core: false, name: "OGLE (-IV/V)", wiki: "Optical Gravitational Lensing Experiment",
    img: "bhns_card_images/ogle_iv_v.jpg",
    tstart: 1992, tend: null, spec: { kind: "em", segs: [[14.50, 14.65]] },
    freq: "I-band Galactic bulge monitoring", product: "Photometric microlensing event detection",
    notes: "",
    use: "Long-t_E events → isolated BH candidates (OGLE-2011-BLG-0462)",
    refs: [ { t: "Udalski + 2015", u: ADS("arXiv:1504.05966") }, { t: "Mróz + 2022", u: ADS("arXiv:2207.10729") } ] },
  { band: "optTD", core: true, name: "Nancy Grace Roman Space Telescope", wiki: "Nancy Grace Roman Space Telescope",
    img: "bhns_card_images/nancy_grace_roman_space_telescope.jpg",
    tstart: 2026, tend: 2036, future: true, spec: { kind: "em", segs: [[14.11, 14.80]] },
    freq: "0.48–2.3 µm; 0.281 deg² WFI", product: "Wide-field IR imaging, slitless spectroscopy, precision astrometry; Galactic Bulge Time Domain Survey",
    notes: "Launch 30 Aug 2026; 5-yr prime mission (+5 expected).",
    use: "Astrometric+photometric µ-lensing → isolated-BH mass census (100s–1000 expected); high-z SNe & PISN",
    refs: [ { t: "Spergel + 2015", u: ADS("arXiv:1503.03757") }, { t: "Lam + 2023", u: ADSQ("Lam Roman isolated black holes microlensing") } ] },
  { band: "optTD", core: false, name: "Euclid", wiki: "Euclid (spacecraft)",
    img: "bhns_card_images/euclid.jpg",
    tstart: 2023, tend: 2030, spec: { kind: "em", segs: [[14.18, 14.74]] },
    freq: "VIS 550–900 nm + NISP Y/J/H", product: "Wide+deep imaging, NIR grism",
    notes: "~6-yr survey.",
    use: "Serendipitous transients in deep fields; lensed SNe",
    refs: [ { t: "Euclid Collab. (Mellier) + 2025", u: ADS("arXiv:2405.13491") } ] },

  // ---------- Optical / IR — astrometry & spectroscopy ----------
  { band: "optSp", core: true, name: "Gaia", wiki: "Gaia (spacecraft)",
    img: "bhns_card_images/gaia.jpg",
    tstart: 2014, tend: 2025, spec: { kind: "em", segs: [[14.46, 14.96]] },
    freq: "G band 330–1050 nm; RVS 845–872 nm", product: "µas astrometry (>10⁹ sources), photometry, RVs to G≈14; astrometric orbits",
    notes: "Observations ended Jan 2025; DR4 in Dec 2026, DR5 ~2030 — the discoveries are still ahead.",
    use: "Gaia BH1–3 & NS companions via astrometric wobble; runaway stars (kicks); µ-lensing",
    refs: [ { t: "Gaia Collab. 2016", u: ADS("arXiv:1609.04153") }, { t: "El-Badry + 2023", u: ADS("arXiv:2209.06833") }, { t: "Panuzzo + 2024", u: ADS("arXiv:2404.10486") } ] },
  { band: "optSp", core: true, name: "SDSS-V Milky Way Mapper", wiki: "Sloan Digital Sky Survey",
    img: "bhns_card_images/sdss_v_milky_way_mapper.jpg",
    tstart: 2020, tend: 2028, spec: { kind: "em", segs: [[14.25, 14.92]] },
    freq: "BOSS 360–1000 nm (R~2000); APOGEE 1.51–1.70 µm (R~22,500)", product: "Multi-epoch spectroscopy of ~6M stars → RV curves; incl. ~600k OB(A) stars",
    notes: "Observing from both hemispheres (APO + LCO).",
    use: "Industrial-scale dormant-CO candidate selection via RV variability",
    refs: [ { t: "Kollmeier + 2017", u: ADS("arXiv:1711.03234") } ] },
  { band: "optSp", core: false, name: "4MOST / WEAVE", wiki: "4MOST",
    img: "bhns_card_images/4most_weave.jpg",
    tstart: 2023, tend: null, spec: { kind: "em", segs: [[14.49, 14.91]] },
    freq: "370–950 nm, R~4000–20,000", product: "Massively multiplexed (1000–2400 fibre) spectroscopic surveys",
    notes: "4MOST on VISTA (south) from ~2026; WEAVE on the WHT (north) since 2023.",
    use: "RV confirmation of Gaia CO binaries; stripped-star spectra; r-process abundances",
    refs: [ { t: "de Jong + 2019", u: ADS("arXiv:1903.02464") }, { t: "Jin + 2024", u: ADS("arXiv:2212.03981") } ] },
  { band: "optSp", core: true, name: "VLT (+ GRAVITY/GRAVITY+)", wiki: "Very Large Telescope",
    img: "bhns_card_images/vlt_gravity_gravity.jpg",
    tstart: 1998, tend: null, spec: { kind: "em", segs: [[13.18, 15.00]] },
    freq: "300 nm – 20 µm; K-band interferometry", product: "UVES/X-shooter/MUSE spectroscopy; 10–100 µas interferometric astrometry",
    notes: "GRAVITY+ upgrade ongoing.",
    use: "RV orbits of quiescent BH binaries (VFTS 243); Galactic-centre S stars around Sgr A*",
    refs: [ { t: "GRAVITY Collab. 2017", u: ADS("arXiv:1705.02345") }, { t: "Shenar + 2022", u: ADS("arXiv:2207.07675") } ] },
  { band: "optSp", core: false, name: "ELT (39 m)", wiki: "Extremely Large Telescope",
    img: "bhns_card_images/elt_39_m.jpg",
    tstart: 2030, tend: null, future: true, spec: { kind: "em", segs: [[13.18, 14.93]] },
    freq: "0.35–20 µm", product: "AO imaging + spectroscopy at 39-m sensitivity",
    notes: "First light ~2029/30.",
    use: "Kilonova spectra to large distances (ET era); faint CO companions",
    refs: [ { t: "Padovani & Cirasuolo 2023", u: ADSQ("Padovani Cirasuolo Extremely Large Telescope 2023") } ] },
  { band: "optSp", core: true, name: "JWST", wiki: "James Webb Space Telescope",
    img: "bhns_card_images/jwst.jpg",
    tstart: 2022, tend: null, spec: { kind: "em", segs: [[13.03, 14.70]] },
    freq: "0.6–28 µm", product: "IR imaging + low/medium-resolution spectroscopy",
    notes: "~20 years of fuel.",
    use: "Kilonova nebular spectra (Te in GRB 230307A); SN progenitors; dust-obscured transients",
    refs: [ { t: "Gardner + 2023", u: ADS("arXiv:2304.04869") }, { t: "Levan + 2024", u: ADS("arXiv:2307.02098") } ] },
  { band: "optSp", core: false, name: "HST", wiki: "Hubble Space Telescope",
    img: "bhns_card_images/hst.jpg",
    tstart: 1990, tend: null, spec: { kind: "em", segs: [[14.25, 15.52]] },
    freq: "90 nm – 1.7 µm", product: "UV–NIR imaging/spectroscopy; ~0.2 mas relative astrometry",
    notes: "Re-entry in the 2030s without an orbital boost.",
    use: "Astrometric µ-lensing isolated BH (Sahu et al. 2022); UV spectra of stripped stars",
    refs: [ { t: "Sahu + 2022", u: ADS("arXiv:2201.13296") } ] },

  // ---------- Ultraviolet ----------
  { band: "uv", core: true, name: "ULTRASAT", wiki: "ULTRASAT",
    img: "bhns_card_images/ultrasat.jpg",
    tstart: 2027, tend: 2033, future: true, spec: { kind: "em", segs: [[15.01, 15.12]] },
    freq: "NUV 230–290 nm; 204 deg² FoV", product: "First wide-field UV time-domain survey; alerts within 20 min",
    notes: "Launch Q4 2027 to GEO; 3-yr prime (+3); slews to >50% of the sky within minutes.",
    use: "SN shock breakout & shock cooling; early kilonova UV; grasp 300× GALEX",
    refs: [ { t: "Shvartzvald + 2024", u: ADS("arXiv:2304.14482") } ] },
  { band: "uv", core: true, name: "UVEX", wiki: "Ultraviolet Explorer",
    img: "bhns_card_images/uvex.jpg",
    tstart: 2030, tend: 2032, future: true, spec: { kind: "em", segs: [[15.05, 15.33]] },
    freq: "FUV 139–190 + NUV 203–270 nm; R>1000 spectroscopy", product: "All-sky UV imaging survey + rapid ToO + UV spectroscopy",
    notes: "NASA MIDEX; launch ~2030; 2-yr prime mission.",
    use: "Hot stripped-star census (LMC/SMC); kilonova UV evolution; GW follow-up",
    refs: [ { t: "Kulkarni + 2021", u: ADS("arXiv:2111.15608") } ] },
  { band: "uv", core: false, name: "GALEX (archival)", wiki: "GALEX",
    img: "bhns_card_images/galex_archival.jpg",
    tstart: 2003, tend: 2013, spec: { kind: "em", segs: [[15.03, 15.35]] },
    freq: "FUV 135–175 + NUV 175–280 nm", product: "All-sky UV imaging archive",
    notes: "Mission ended 2013; the archive remains a key resource.",
    use: "UV-excess selection of stripped-star candidates today",
    refs: [ { t: "Martin + 2005", u: ADS("2005ApJ...619L...1M") } ] },

  // ---------- X-ray ----------
  { band: "xray", core: true, name: "Swift (Neil Gehrels Obs.)", wiki: "Neil Gehrels Swift Observatory",
    img: "bhns_card_images/swift_neil_gehrels_obs.jpg",
    tstart: 2004, tend: null, spec: { kind: "em", segs: [[14.70, 15.25], [16.86, 19.56]] },
    freq: "BAT 15–150 keV; XRT 0.3–10 keV; UVOT 170–600 nm", product: "GRB discovery + autonomous arcsec localization within minutes; UV/optical photometry",
    notes: "",
    use: "Short-GRB afterglows; XRB outburst monitoring; kilonova UV (GW170817)",
    refs: [ { t: "Gehrels + 2004", u: ADS("2004ApJ...611.1005G") } ] },
  { band: "xray", core: true, name: "Einstein Probe", wiki: "Einstein Probe",
    img: "bhns_card_images/einstein_probe.jpg",
    tstart: 2024, tend: null, spec: { kind: "em", segs: [[16.86, 18.38]] },
    freq: "WXT 0.5–4 keV (lobster-eye, 3600 deg²); FXT 0.3–10 keV", product: "Wide-field soft-X-ray transient monitor + rapid follow-up telescope",
    notes: "CAS mission with ESA & MPE participation; 3+ yr.",
    use: "Fast X-ray transients, new XRB outbursts, TDEs, GW & FRB counterpart searches",
    refs: [ { t: "Yuan + 2022", u: ADS("arXiv:2209.09763") } ] },
  { band: "xray", core: false, name: "SVOM", wiki: "Space Variable Objects Monitor",
    img: "bhns_card_images/svom.jpg",
    tstart: 2024, tend: null, spec: { kind: "em", segs: [[16.68, 19.56]] },
    freq: "ECLAIRs 4–150 keV; MXT 0.2–10 keV; + GRM, VT optical", product: "GRB discovery & built-in multiband follow-up chain",
    notes: "CNES/CAS mission; launched Jun 2024.",
    use: "GRBs incl. high-z; complements Swift",
    refs: [ { t: "Wei + 2016", u: ADS("arXiv:1610.06892") } ] },
  { band: "xray", core: true, name: "NICER", wiki: "Neutron Star Interior Composition Explorer",
    img: "bhns_card_images/nicer.jpg",
    tstart: 2017, tend: null, spec: { kind: "em", segs: [[16.68, 18.46]] },
    freq: "0.2–12 keV; ~100 ns timing", product: "Soft X-ray timing; phase-resolved spectroscopy",
    notes: "Mounted on the ISS.",
    use: "NS mass–radius from pulse-profile modelling → EoS (PSR J0030, J0740)",
    refs: [ { t: "Gendreau + 2016", u: ADSQ("Gendreau NICER 2016 SPIE") }, { t: "Riley + 2021", u: ADS("arXiv:2105.06980") }, { t: "Miller + 2021", u: ADS("arXiv:2105.06979") } ] },
  { band: "xray", core: false, name: "NuSTAR", wiki: "NuSTAR",
    img: "bhns_card_images/nustar.jpg",
    tstart: 2012, tend: null, spec: { kind: "em", segs: [[17.86, 19.28]] },
    freq: "3–79 keV (focusing)", product: "Hard X-ray imaging spectroscopy",
    notes: "",
    use: "ULX pulsars; reflection-based BH spins; magnetar outbursts",
    refs: [ { t: "Harrison + 2013", u: ADS("arXiv:1301.7307") } ] },
  { band: "xray", core: false, name: "Chandra", wiki: "Chandra X-ray Observatory",
    img: "bhns_card_images/chandra.jpg",
    tstart: 1999, tend: null, spec: { kind: "em", segs: [[16.38, 18.38]] },
    freq: "0.1–10 keV; 0.5″ resolution", product: "Sub-arcsecond X-ray imaging + gratings spectroscopy",
    notes: "",
    use: "Extragalactic XRB/ULX populations; NS cooling; GW170817 X-ray afterglow",
    refs: [ { t: "Weisskopf + 2000", u: ADSQ("Weisskopf Chandra X-ray Observatory 2000") } ] },
  { band: "xray", core: false, name: "XMM-Newton", wiki: "XMM-Newton",
    img: "bhns_card_images/xmm_newton.jpg",
    tstart: 1999, tend: null, spec: { kind: "em", segs: [[16.56, 18.46]] },
    freq: "0.15–12 keV", product: "High-throughput spectroscopy & timing",
    notes: "",
    use: "Quiescent LMXBs; magnetars; ULX monitoring",
    refs: [ { t: "Jansen + 2001", u: ADS("2001A&A...365L...1J") } ] },
  { band: "xray", core: false, name: "eROSITA (SRG)", wiki: "EROSITA",
    img: "bhns_card_images/erosita_srg.jpg",
    tstart: 2019, tend: 2022, spec: { kind: "em", segs: [[16.68, 18.28]] },
    freq: "0.2–8 keV", product: "All-sky X-ray survey every 6 months",
    notes: "Survey paused Feb 2022; eRASS1 catalogue released 2024.",
    use: "New XRBs & transients; population statistics",
    refs: [ { t: "Predehl + 2021", u: ADS("arXiv:2010.03477") } ] },
  { band: "xray", core: false, name: "XRISM", wiki: "X-Ray Imaging and Spectroscopy Mission",
    img: "bhns_card_images/xrism.jpg",
    tstart: 2023, tend: null, spec: { kind: "em", segs: [[16.86, 18.46]] },
    freq: "0.3–12 keV; Resolve R~1200", product: "Microcalorimeter high-resolution spectroscopy",
    notes: "",
    use: "Disc winds & plasma velocities in XRBs and SN remnants",
    refs: [ { t: "Tashiro + 2020", u: ADSQ("Tashiro XRISM status 2020") } ] },
  { band: "xray", core: false, name: "IXPE", wiki: "Imaging X-ray Polarimetry Explorer",
    img: "bhns_card_images/ixpe.jpg",
    tstart: 2021, tend: null, spec: { kind: "em", segs: [[18.06, 18.28]] },
    freq: "2–8 keV (polarimetry)", product: "Imaging X-ray polarimetry",
    notes: "",
    use: "Accretion geometry of XRBs; magnetar magnetospheres",
    refs: [ { t: "Weisskopf + 2022", u: ADS("arXiv:2112.01269") } ] },
  { band: "xray", core: false, name: "NewAthena", wiki: "Advanced Telescope for High Energy Astrophysics",
    img: "bhns_card_images/newathena.jpg",
    tstart: 2037, tend: null, future: true, spec: { kind: "em", segs: [[16.68, 18.46]] },
    freq: "0.2–12 keV", product: "X-IFU microcalorimeter + Wide Field Imager at large collecting area",
    notes: "ESA adoption expected ~2027; launch ~2037.",
    use: "Faint EoS targets; high-z GRB afterglows; ET-era X-ray counterpart workhorse",
    refs: [ { t: "Nandra + 2013", u: ADS("arXiv:1306.2307") } ] },

  // ---------- Gamma-ray ----------
  { band: "gamma", core: true, name: "Fermi (GBM + LAT)", wiki: "Fermi Gamma-ray Space Telescope",
    img: "bhns_card_images/fermi_gbm_lat.jpg",
    tstart: 2008, tend: null, spec: { kind: "em", segs: [[19.29, 25.86]] },
    freq: "GBM 8 keV–40 MeV; LAT 20 MeV–300 GeV", product: "All-sky GRB monitor (GBM) + GeV survey (LAT)",
    notes: "",
    use: "GRB 170817A (1.7 s after the GW!); magnetar giant flares; γ-ray (spider) pulsars",
    refs: [ { t: "Meegan + 2009", u: ADS("arXiv:0908.0450") }, { t: "Atwood + 2009", u: ADS("arXiv:0902.1089") }, { t: "Abbott + 2017", u: ADS("arXiv:1710.05834") } ] },
  { band: "gamma", core: false, name: "INTEGRAL", wiki: "INTEGRAL",
    img: "bhns_card_images/integral.jpg",
    tstart: 2002, tend: 2024, spec: { kind: "em", segs: [[19.56, 21.38]] },
    freq: "15 keV–10 MeV", product: "Hard-X/soft-γ imaging spectroscopy",
    notes: "Science operations ended; archival.",
    use: "Independent GRB 170817A detection; ⁴⁴Ti & e⁺e⁻ 511 keV lines",
    refs: [ { t: "Winkler + 2003", u: ADS("2003A&A...411L...1W") }, { t: "Savchenko + 2017", u: ADS("arXiv:1710.05449") } ] },
  { band: "gamma", core: false, name: "CTAO", wiki: "Cherenkov Telescope Array",
    img: "bhns_card_images/ctao.jpg",
    tstart: 2026, tend: null, future: true, spec: { kind: "em", segs: [[24.68, 28.86]] },
    freq: "20 GeV–300 TeV", product: "Imaging atmospheric Cherenkov arrays (N+S)",
    notes: "Partial arrays observing; full northern + southern arrays ~late 2020s.",
    use: "TeV GRB afterglows; PWNe; µquasar jets",
    refs: [ { t: "CTA Consortium 2019", u: ADS("arXiv:1709.07997") } ] },
  { band: "gamma", core: false, name: "COSI", wiki: "Compton Spectrometer and Imager",
    img: "bhns_card_images/cosi.jpg",
    tstart: 2027, tend: null, future: true, spec: { kind: "em", segs: [[19.68, 21.08]] },
    freq: "0.2–5 MeV", product: "Compton imaging, spectroscopy & polarimetry; all-sky daily",
    notes: "NASA SMEX; launch 2027.",
    use: "⁵⁶Ni/⁴⁴Ti decay lines from SNe; Galactic 511 keV positron map; MeV transients",
    refs: [ { t: "Tomsick + 2023", u: ADS("arXiv:2308.12362") } ] },
];
